version: "3.8"
services:
  
  mariadb:
    container_name: mariadb_db
    environment:
      - MYSQL_DATABASE=jwt-app
      - MYSQL_USER=jwt-app
      - MYSQL_PASSWORD=jwt-app123
      - MYSQL_ROOT_PASSWORD=rootjwt-app123
    restart: unless-stopped
    image: mariadb:latest
    volumes:
      - ./dbdata:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'
    ports:
      - 3306:3306
      
  redis:
    image: redis:latest
    ports:
      - 6379:6379

