version: "3.8"

services:
  application:
    container_name: app
    image: jwtsplittoken:latest
    build:
      context: .
    ports:
      - 8090:80
    environment:
      CONNECTION_STRING: root:rootjwt-app123@tcp(mariadb_db:3306)/jwt-app?parseTime=true
      PORT: ":80"
      ACCESS_TOKEN_MAX_AGE: 10
      JWT_KEY: p3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C
    depends_on:
      - mariadb
      - redis

  mariadb:
    container_name: mariadb_db
    environment:
      MYSQL_DATABASE: jwt-app
      MYSQL_USER: jwt-app
      MYSQL_PASSWORD: jwt-app123
      MYSQL_ROOT_PASSWORD: rootjwt-app123
    restart: unless-stopped
    image: mariadb:latest
    volumes:
      - ./dbdata:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'
    ports:
      - 3306:3306
      
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
