@host = localhost:8090

// Access a Secured API Endpoint
GET http://{{host}}/api/v1/access-management/time-ir HTTP/1.1
content-type: application/text
authorization: 4T7ODljfAUgi7_NQMij4VvCr4FpNszg7I3WOLDTMyHQ

###